[package]
name = "quantus_ur"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
ur-parse-lib = { version = "1.0.6", default-features = false }
ur = { package = "keystone-ur", version = "0.1.1", default-features = false }
minicbor = { version = "0.19", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["ur-parse-lib/std"]
core = ["ur-parse-lib/core"]